version: "3.8"

services:
  app:
    build:
      context: ./app
    container_name: pps_app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - write-db
      - rabbitmq
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

  worker:
    build:
      context: ./app
    container_name: pps_worker
    volumes:
      - ./app:/var/www/html
    depends_on:
      - rabbitmq
      - write-db
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    command: php src/Commands/NotificationWorker.php
    restart: always

  write-db:
    image: mysql:8
    container_name: pps_write_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_write_data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./docker/db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

  read-db:
    image: mysql:8
    container_name: pps_read_db
    restart: always
    environment:
      MYSQL_DATABASE: pps_read
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3307:3306"
    volumes:
      - mysql_read_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pps_rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pps_phpmyadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PMA_HOST: write-db
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - write-db

volumes:
  mysql_write_data:
  mysql_read_data:
